http:
  address: :80
  workers:
    user: "app"
    command: "php /app/index.php"

static:
  dir:   "/app/public"
  forbid: [".php", ".htaccess"]

headers:
  response:
    "X-Frame-Options": "deny"
    "X-Content-Type-Options": "nosniff"
    "X-XSS-Protection": "1; mode=block"
    "Referrer-Policy": "no-referrer-when-downgrade"

rpc:
  enable: true
  listen: tcp://:6001

health:
  address: :2113

limit:
  interval: 1
  services:
    http:
      maxMemory: 100
      TTL: 0
      idleTTL: 0
      execTTL: 60
