version: '3'
services:
  app:
    container_name: app
    build: .
    image: edmitry/php-fpm
    restart: always
    volumes:
      - socks:/socks
      - .:/app
      - ./docker/app/conf/php/dev.ini:/usr/local/etc/php/conf.d/dev.ini
      - ./docker/app/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    env_file:
      - ./dev.env
    environment:
      - PHAN_DISABLE_XDEBUG_WARN=1
      - PHAN_ALLOW_XDEBUG=0
      - PHP_IDE_CONFIG=serverName=app
    healthcheck:
      test: ["CMD", "curl", "-fI", "nginx"]
      interval: 1s
      timeout: 1s
      retries: 10
  nginx:
    container_name: nginx
    image: edmitry/nginx
    restart: always
    volumes:
      - socks:/socks
      - ./public:/web
    ports:
      - 80:80
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "curl", "-fI", "http://localhost/nginx-status"]
      interval: 1s
      timeout: 1s
      retries: 10
volumes:
  socks:
