version: '3'
services:
    app:
        container_name: app
        build: .
        restart: always
        volumes:
            - socks:/socks
            - ./public:/app/public
        healthcheck:
            test: ["CMD", "curl", "-fI", "nginx"]
            interval: 1s
            timeout: 1s
            retries: 10
    nginx:
        container_name: nginx
        image: edmitry/nginx
        restart: always
        volumes:
            - socks:/socks
            - ./public:/web
        ports:
            - 80:80
        depends_on:
            - app
        healthcheck:
            test: ["CMD", "curl", "-fI", "localhost/nginx-status"]
            interval: 1s
            timeout: 1s
            retries: 10
volumes:
    socks:
