version: '3'
services:
  app:
    container_name: app
    build: .
    image: edmitry/php:rr
    restart: always
    volumes:
      - .:/app
      - ./docker/app/conf/php/dev.ini:/usr/local/etc/php/conf.d/dev.ini
      - ./docker/app/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/app/conf/rr/dev.yml:/usr/local/etc/roadrunner/rr.yml
    ports:
      - 80:80
    env_file:
      - ./.env
    environment:
      - PHAN_DISABLE_XDEBUG_WARN=1
      - PHAN_ALLOW_XDEBUG=0
      - PHP_IDE_CONFIG=serverName=app
    command: ["-d"]
    healthcheck:
      test: ["CMD", "curl", "-fI", "localhost:2113"]
      interval: 1s
      timeout: 1s
      retries: 10
