version: '3'
services:
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - 80:80
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "-fI", "localhost:2113"]
      interval: 1s
      timeout: 1s
      retries: 10
